import React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import axios from "axios";
import { useState } from "react";

export default function Form() {
    const [name, setName] = useState("");
    const [email, setEmail] = useState("");
    const router = useRouter();

    // Handle the form submission
    const handleSubmit = (event) => {
        event.preventDefault();

        axios
            .post("http://127.0.0.1:8000/api/form", {
                name,
                email,
            })
            .then((response) => {
                // handle success
                console.log(response.data);
                router.push("/fetchRequests");
            })
            .catch((error) => {
                // handle error
                console.log(error);
                //   router.push("/error");
            });
    };

    return (
        <div>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>Form Example</title>
                <link rel="icon" href="/favicon.ico" />
                {/* <meta name="csrf-token" content="{{ csrf_token() }}" /> */}
            </Head>

            <main>
                <h1>Form Example</h1>
                <form onSubmit={handleSubmit}>
                    {/* @csrf */}
                    <div>
                        <label htmlFor="name">Name:</label>
                        <input
                            id="name"
                            value={name}
                            type="text"
                            placeholder="Enter your name"
                            required
                            onChange={(event) => setName(event.target.value)}
                        />
                    </div>
                    <div>
                        <label htmlFor="email">Email:</label>
                        <input
                            id="email"
                            value={email}
                            type="email"
                            placeholder="Enter your email"
                            required
                            onChange={(event) => setEmail(event.target.value)}
                        />
                    </div>
                    <button type="submit">Submit</button>
                </form>
                <Link href="/">
                    <a>Go back home</a>
                </Link>
            </main>
        </div>
    );
}
